# File automatically-generated by STM32CubeMX - Do not modify
cmake_minimum_required(VERSION 3.22)
# STM32CubeMX generated symbols (macros)
set(MX_Defines_Syms 
	NO_ATOMIC_64_SUPPORT 
	METAL_INTERNAL 
	METAL_MAX_DEVICE_REGIONS=2 
	VIRTIO_DEVICE_ONLY 
	CORE_CM33 
	USE_HAL_DRIVER 
	STM32MP257Dxx
    $<$<CONFIG:Debug>:DEBUG>
)
# STM32CubeMX generated include paths
set(MX_Include_Dirs
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/OPENAMP
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/RTOS2/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Utilities/CoproSync
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Device/ST/STM32MP2xx/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/virtual_driver
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/CMSIS/Include
)
# STM32CubeMX generated application sources
set(MX_Application_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/main.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/freertos.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/adc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/fdcan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/hpdma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/i2c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/ipcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/spi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/usart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/stm32mp2xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/stm32mp2xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/stm32mp2xx_hal_timebase_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/sysmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/Core/Src/syscalls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/OPENAMP/mbox_ipcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/OPENAMP/open_amp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/OPENAMP/rsc_table.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../CM33/OPENAMP/openamp_log.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Startup/startup_stm32mp257dxx_m33.s
)

# STM32 HAL/LL Drivers
set(STM32_Drivers_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Common/System/system_stm32mp2xx_m33.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_tim_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_adc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_adc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_dma_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_rcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_rcc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_hsem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_pwr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_pwr_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_cortex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_icache.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_exti.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_fdcan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_i2c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_i2c_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_ipcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_spi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_spi_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_uart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32MP2xx_HAL_Driver/Src/stm32mp2xx_hal_uart_ex.c
)

# Drivers Midllewares

set(Utilities_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Utilities/CoproSync/copro_sync.c
)
set(FreeRTOS_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/croutine.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/list.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/queue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/tasks.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/timers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/Common/mpu_wrappers_v2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/Common/mpu_wrappers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/mpu_wrappers_v2_asm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/port.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c
)
set(OpenAMP_Src
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/device.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/log.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/init.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/io.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/shmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/irq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/softirq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/version.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/condition.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/device.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/init.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/io.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/shmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/irq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/time.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/remoteproc/remoteproc_virtio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/rpmsg/rpmsg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/rpmsg/rpmsg_virtio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/virtio/virtio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/open-amp/lib/virtio/virtqueue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/virtual_driver/virt_i2c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/virtual_driver/virt_intc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/virtual_driver/virt_uart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/template/sys.c
)
# Link directories setup
set(MX_LINK_DIRS

)
# Project libraries
set (MX_LINK_LIBS 
    STM32_Drivers
    ${TOOLCHAIN_LINK_LIBRARIES}
    Utilities	FreeRTOS	OpenAMP	
    
)
# Interface library for includes and symbols
add_library(stm32cubemx INTERFACE)
target_include_directories(stm32cubemx INTERFACE ${MX_Include_Dirs})
target_compile_definitions(stm32cubemx INTERFACE ${MX_Defines_Syms})

# Create STM32_Drivers static library
add_library(STM32_Drivers OBJECT)
target_sources(STM32_Drivers PRIVATE ${STM32_Drivers_Src})
target_link_libraries(STM32_Drivers PUBLIC stm32cubemx)

# Create Utilities static library
add_library(Utilities OBJECT)
target_sources(Utilities PRIVATE ${Utilities_Src})
target_link_libraries(Utilities PUBLIC stm32cubemx)

# Create FreeRTOS static library
add_library(FreeRTOS OBJECT)
target_sources(FreeRTOS PRIVATE ${FreeRTOS_Src})
target_link_libraries(FreeRTOS PUBLIC stm32cubemx)

# Create OpenAMP static library
add_library(OpenAMP OBJECT)
target_sources(OpenAMP PRIVATE ${OpenAMP_Src})
target_link_libraries(OpenAMP PUBLIC stm32cubemx)


# Add STM32CubeMX generated application sources to the project
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MX_Application_Src})

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MX_LINK_DIRS})

# Add libraries to the project
target_link_libraries(${CMAKE_PROJECT_NAME} ${MX_LINK_LIBS})

# Add the map file to the list of files to be removed with 'clean' target
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES ADDITIONAL_CLEAN_FILES ${CMAKE_PROJECT_NAME}.map)




# Pre_build commands
# add_custom_command(TARGET ${CMAKE_PROJECT_NAME} PRE_BUILD 
#   COMMAND ${CMAKE_OBJCOPY} -O ihex ${CMAKE_PROJECT_NAME}.elf ${CMAKE_PROJECT_NAME}.hex
#   COMMAND ${CMAKE_OBJCOPY} -O binary ${CMAKE_PROJECT_NAME}.elf ${CMAKE_PROJECT_NAME}.bin
#   COMMAND cmake -S ../../Middlewares/Third_Party/OpenAMP/libmetal/ -B libmetal  -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/stm32mp-freertos-gcc.cmake 
#   COMMENT "Executing PRE build command")


# Validate that STM32CubeMX code is compatible with C standard
if((CMAKE_C_STANDARD EQUAL 90) OR (CMAKE_C_STANDARD EQUAL 99))
    message(ERROR "Generated code requires C11 or higher")
endif()