# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT MULTI_CONTEXT CACHE STRING "Type of multi-context")
#-----------------------Build CM33 Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*CM33.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " CM33)
    ExternalProject_Add(AFC7
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/CM33/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/CM33
        PREFIX                      CM33
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DTFM_BUILD_DIR=${TFM_BUILD_DIR}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/CM33/build")
	set(ST_MULTI_CONTEXT_CM33_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/CM33/build/AFC7${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to cm33 project target")
endif()

